# Generated by Django 4.2.7 on 2023-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.TextField(max_length=9)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birth_date', models.DateTimeField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('building_number', models.IntegerField()),
                ('apartment_number', models.IntegerField()),
                ('cellphone_number', models.TextField(max_length=10)),
            ],
        ),
    ]
